include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    depend_on_referenced_packages: false
    prefer_single_quotes: true
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_type_to_string: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_web_libraries_in_flutter: true
    camel_case_extensions: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    hash_and_equals: true
    implementation_imports: true
    implicit_reopen: true
    invalid_case_patterns: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_private_types_in_public_api: true
    lines_longer_than_80_chars: true
    no_default_cases: true
    no_duplicate_case_values: true
    no_literal_bool_comparisons: true
    no_logic_in_create_state: true
    noop_primitive_operations: true
    package_names: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_literal_in_constant_pattern: true
    unawaited_futures: true
    unnecessary_async: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_late: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_function_type_syntax_for_parameters: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    valid_regexps: true
