name: tv_plus
description: "Smart TV toolkit"
version: 0.4.0
repository: https://github.com/dinaraparanid/tv_plus

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

workspace:
  - example
  - packages/cupertino
  - packages/foundation
  - packages/material
  - packages/one_ui

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_svg: ^2.1.0
  vector_graphics: ^1.1.19
  tv_plus_foundation: ^0.4.0
  tv_plus_cupertino: ^0.4.0
  tv_plus_material: ^0.4.0
  tv_plus_one_ui: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.11.0
  flutter_pre_commit: ^0.2.4
  test: ^1.29.0
  melos: ^7.4.0

flutter:
  generate: true
  plugin:
    platforms:
      android:
        package: com.paranid5.tv_plus
        pluginClass: TvPlusPlugin

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.9.2
        flutter: '>=3.3.0'
      usePubspecOverrides: true
      hooks:
        post: melos build_runner

    version:
      message: "chore(release): publish packages"
      branch: master
      linkToCommits: true
      workspaceChangelog: true
      updateGitTagRefs: true

  scripts:
    build_runner:
      run: dart run build_runner build
      description: Code generation
      exec:
        concurrency: 1

    clean:
      run: flutter clean
      description: Clean all Flutter packages
      exec:
        concurrency: 1

    test:
      run: flutter test
      description: Run tests
      packageFilters:
        dirExists: test
      exec:
        concurrency: 4
        failFast: true

    test_coverage:
      run: flutter test --coverage
      description: Check test coverage
      packageFilters:
        dirExists: test
      exec:
        concurrency: 4
        failFast: true

    combine_coverage:
      run: melos exec -- "\$MELOS_ROOT_PATH/scripts/combine_coverage.sh"
      description: Generate full coverage report
      packageFilters:
        dirExists: test
