sonar.projectKey=dinaraparanid_tv_plus
sonar.organization=paranid5

sonar.projectName=tv_plus
sonar.projectVersion=0.4.0

sonar.sources=lib,example,packages,pubspec.yaml

sonar.dart.lcov.reportPaths=coverage_report/lcov.info

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/test/**,**/build/**,**/ios/**,**/android/**,**/web/**,**/macos/**,lib/**/*.g.dart,**/mock/**,**/*mock*.*
