name: SonarQube

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.2

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true

      - name: Generate Test Coverage
        run: melos run test_coverage --no-select

      - name: Combine Test Coverage
        run: melos run combine_coverage --no-select

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload SonarQube problems report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-problems-report
          path: ${{ github.workspace }}/build/reports/problems/problems-report.html