name: SonarQube

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.2

      - name: Get Dependencies
        run: flutter pub get

      - name: Perform code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate Test Coverage
        run: flutter test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload SonarQube problems report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-problems-report
          path: ${{ github.workspace }}/build/reports/problems/problems-report.html